export { DashboardPage as Dashboard } from './DashboardPage';
export { DashboardPage } from './DashboardPage';
export { ChatPage as AIChat } from './ChatPage';
export { ChatPage } from './ChatPage';
export { KnowledgePage as Knowledge } from './KnowledgePage';
export { KnowledgePage } from './KnowledgePage';
export { MemoriesPage as Memories } from './MemoriesPage';
export { MemoriesPage } from './MemoriesPage';
export { GoalsPage as Goals } from './GoalsPage';
export { GoalsPage } from './GoalsPage';
export { ProjectsPage as Projects } from './ProjectsPage';
export { ProjectsPage } from './ProjectsPage';
export { IdeasPage as Ideas } from './IdeasPage';
export { IdeasPage } from './IdeasPage';
export { LearningsPage as Learnings } from './LearningsPage';
export { LearningsPage } from './LearningsPage';
export { SettingsPage as Settings } from './SettingsPage';
export { SettingsPage } from './SettingsPage';
export { TimelinePage as Timeline } from './TimelinePage';
export { TimelinePage } from './TimelinePage';
